apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-ambulance-webapi
spec:
  template:
    spec:
      initContainers:
        - name: init-postgres
          image: postgres:17
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for Postgres...";
              until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER; do
                sleep 2;
              done;

              echo "Running init script...";
              PGPASSWORD=$POSTGRES_PASSWORD psql \
                -h $POSTGRES_HOST \
                -p $POSTGRES_PORT \
                -U $POSTGRES_USER \
                -d $POSTGRES_DB \
                -f /scripts/init-db.sql

          env:
            - name: POSTGRES_HOST
              value: postgres-db

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ambulance-db-secret
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ambulance-db-secret
                  key: password

            - name: POSTGRES_DB
              value: ambulance

      containers:
        - name: ml-ambulance-webapi-container
          env:
            - name: POSTGRES_HOST
              value: postgres-db

            - name: POSTGRES_PORT
              value: "5432"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ambulance-db-secret
                  key: username

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ambulance-db-secret
                  key: password

            - name: POSTGRES_DB
              value: ambulance

            - name: POSTGRES_SSLMODE
              value: disable

            - name: POSTGRES_TIMEOUT_SECONDS
              value: "5"