apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../install

components:
  - ../components/postgreskubectl exec -it ml-ambulance-webapi-9d49d75cb-zn272 -n wac-hospital -c ml-ambulance-webapi-container -- printenv