apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

configMapGenerator:
  - name: postgres-connection
    options:
      disableNameSuffixHash: true
    literals:
      - host=postgres-db
      - port=5432
      - database=ambulance

secretGenerator:
  - name: ambulance-db-secret
    options:
      disableNameSuffixHash: true
    literals:
      - username=admin
      - password=admin