/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlytvynova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type ExaminationsPatientAPI interface {


    // CreateExamination Post /api/examinations/:patientId
    // Prints examinations of patient 
     CreateExamination(c *gin.Context)

    // DeleteExamination Delete /api/examinations/:patientId
    // Deletes specific examination for specific patient 
     DeleteExamination(c *gin.Context)

    // GetExaminations Get /api/examinations/:patientId
    // Provides the examinations list 
     GetExaminations(c *gin.Context)

    // UpdateExamination Put /api/examinations/:patientId
    // Updates specific examinations definition 
     UpdateExamination(c *gin.Context)

}