/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlytvynova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type ExaminationsAPI interface {


    // CreateExamination Post /api/examinations/:patientId/:id
    // Saves new examination definition 
     CreateExamination(c *gin.Context)

    // DeleteExamination Delete /api/examinations/:patientId/:id
    // Deletes specific examination for specific patient 
     DeleteExamination(c *gin.Context)

    // UpdateExamination Put /api/examinations/:patientId/:id
    // Updates specific examination definition 
     UpdateExamination(c *gin.Context)

}