/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xlytvynova@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

type WaitingListEntry struct {

	// Unique id of the entry in this waiting list
	IdPatient int32 `json:"id_patient"`

	// Name of patient in waiting list
	Name string `json:"name"`

	// Timestamp since when the patient entered the waiting list
	Fullname string `json:"fullname"`
}
